services:
  app_db:
    ports:
      - 5432:5432
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ace_exam_platform #Can be changed but not after deployment
      POSTGRES_USER: ace #Can be changed but not after deployment
      POSTGRES_PASSWORD: replace_password #Change before deployment
    restart: always
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: application
    ports:
      # vvvv----- The exposed port
      - 8081:8081 # <---- The application's port
    environment:
      #Enviroment variables to specify how to link to the database
      DB_NAME: postgresql #Specifies that the database is postgres
      DB_URL: postgresql://app_db:5432/ace_exam_platform #Should end with the same as POSTGRES_DB
      DB_USERNAME: ace #Should be the same as the POSTGRES_USER
      DB_PASSWORD: replace_password #Should be the same as the POSTGRES_PASSWORD
      DB_DDL: update #Should be either create, create-drop, update, validate. Set as update to update the database tables/schemas
      DB_DRIVER: org.postgresql.Driver #For the application to know the driver class
      # Enviroment variables to specify emailing
      EMAIL_ADDRESS: example@gmail.com # The company email that should be used to send emails
      EMAIL_PASSWORD: app password # The app password provided from this url: https://myaccount.google.com/apppasswords
    depends_on:
      - app_db
    restart: always